apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-script
data:
  test-script.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export const options = {
      vus: 5,
      duration: '20s',
    };

    export default function () {
      const res = http.get('https://test.k6.io');
      check(res, { 'status is 200': (r) => r.status === 200 });
      sleep(1);
    }